language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

#branches:
#  except:
#    - gh-pages

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mongodb
  - memcached

sudo: false

install:
  - composer self-update
  - composer install --prefer-source
